import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
<<<<<<< HEAD
  labsSidebar: [{ type: 'autogenerated', dirName: '.' }],
  resourcesSidebar: [
    {
      type: 'category',
      label: 'Pagina de resurse',
      link: {
        type: 'doc',
        id: 'resources/index',
      },
      items: ['resources/marking'],
    },
  ],
=======
    labsSidebar: [{ type: 'autogenerated', dirName: 'labs' }],
    homeworkSidebar: [{ type: 'autogenerated', dirName: 'homework' }],
>>>>>>> 5e8149b (feat: added schaffold for labs and homework)

  // But you can create a sidebar manually
  /*
  labsSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
